# Generated by Django 6.0.1 on 2026-01-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_phone_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_created_at',
            new_name='otp_expiry',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
