# Generated by Django 6.0.1 on 2026-01-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_enrollment_course_remove_enrollment_student_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facultyprofile',
            table='academics_facultyprofile',
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='academics_studentprofile',
        ),
    ]
