# Generated by Django 6.0.1 on 2026-02-05 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_batch'),
        ('accounts', '0008_studentprofile_address_studentprofile_admission_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.batch'),
        ),
    ]
