# Generated by Django 6.0.1 on 2026-02-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_fk',
            new_name='role',
        ),
    ]
