# Generated by Django 6.0.1 on 2026-03-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_emailnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailNotification',
        ),
    ]
