# Generated by Django 6.0.1 on 2026-01-30 05:48


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studentprofile_address_studentprofile_admission_year_and_more'),
        ('academics', '0001_initial'),
        ('accounts', '0008_studentprofile_address_studentprofile_admission_year_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
        
            table='academics_course',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='academics_enrollment',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'academics_attendance',
                'unique_together': {('student', 'course', 'date')},
            },
        ),
    ]




