# Generated by Django 6.0.1 on 2026-02-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_batch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'academic_year')},
        ),
    ]
