# Generated by Django 6.0.1 on 2026-02-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_quiz_quizattempt_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
