# Generated by Django 6.0.1 on 2026-02-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_quizanswer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
