# Generated by Django 6.0.1 on 2026-02-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_department_alter_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
